### ISSUE TITLE
hubot "intel map" addition

### ISSUE THREAD

**Issue by kotyy** [hubot-scripts/hubot-ingress#21]
It would be nice if the "hubot intelmap" listener would also respond to "hubot intel map". We have many users who use their phones exclusively, and autocorrect likes to add that space.

**Comment by AgentNormandy** [comment]
I was able to get this to work and added the option to call the command with just "intel" as well as "intel map" as the short form was requested in our local community as well. @therealklanni, still new to this so don't know if I have to create a new pull request or what but here is the output tested on our slack instance. 

![image](https://cloud.githubusercontent.com/assets/10510548/5848486/922f5b08-a19e-11e4-9316-c43caa6bca7f.png)

**Comment by therealklanni** [comment]
Yep, need a new PR for each bugfix or new feature.

I hesitate with the addition of being able to say just "intel", since it's so generic. I wonder if it would clash with any other hubot scripts.
