### ISSUE TITLE
Add "translator" badge

### ISSUE THREAD

**Issue by kotyy** [hubot-scripts/hubot-ingress#23]
The frogs in my area are master glyph hackers and want their badges!

**Comment by AgentNormandy** [comment]
I can add everything to the badges script, @therealklanni did you have a location you got the badge images in the past from or did you just scale them down yourself?

**Comment by therealklanni** [comment]
I think I had to scale some, but most were found on google image search (you can specify an exact size) I think. It was a while ago, hard to recall :)

**Comment by AgentNormandy** [comment]
OK I'll see what I can find.

**Comment by mack-hankins** [comment]
I got them all from here http://niantic.schlarp.com/investigation:apps:ingress:badges

**Comment by therealklanni** [comment]
Oh, yeah that must be where I got them as well.

**Comment by AgentNormandy** [comment]
Let me know if I missed something or typo'ed a badge name. I wanted to add the Shonin but they only had a mockup didn't have a confirmed badge image.

**Comment by AgentNormandy** [comment]
Shouldn't this be closed now?
