### ISSUE TITLE
suggestion to add "You know nothing" meme

### ISSUE THREAD

**Issue by vairis** [hubot-scripts/hubot-ingress#24]
A discussion could be opened to add "you know nothing" meme
http://knowyourmeme.com/memes/you-know-nothing-jon-snow

The text on the gif would be the best, but different approaches are possible.
either 
<text> you know nothing, <text> 
or
<text> you know nothing   // you think you can restart server over lunchtime? you know nothing
or
you know nothing <text>

**Comment by therealklanni** [comment]
Oh, sorry, this project only deals with Ingress-specific commands, such as badges, checking septicycle, and other things related to Ingress.

Please open an issue at [hubot-scripts](https://github.com/github/hubot-scripts/issues) to request this feature (suggested title: add meme to meme-captain.coffee).

**Comment by vairis** [comment]
Sorry, wrong place, feel stupid. Thanks for the info then :)

**Comment by therealklanni** [comment]
No worries! :)
