### ISSUE TITLE
Custom badges

### ISSUE THREAD

**Issue by agreenmamba** [hubot-scripts/hubot-ingress#29]
I have a feature request: The ability for admins to award special badges, whether for serious things like local ops or competitions, or just fun stuff like a bad linker or other fun poking.

**Comment by impleri** [comment]
Relates to #40

**Comment by agreenmamba** [comment]
Not really. #40 relates to Niantic badges. This is about custom badges.

**Comment by impleri** [comment]
Commented in the wrong one. So much for do things half-blindly and before caffeine

**Comment by therealklanni** [comment]
Please reopen this issue/pull-request over at [therealklanni/hubot-ingress](https://github.com/therealklanni/hubot-ingress).
