### ISSUE TITLE
Link Range Calculation

### ISSUE THREAD

**Issue by pklapperich** [hubot-scripts/hubot-ingress#39]
I think a link range command would be useful. Something like:

Hubot link range [level] [amps]
would return the portal distance it could link

Hubot link range [distance] [num agents] [amps]
would return the portal level needed and fewest, lowest level agents needed to build it without amps
if num agents is provided, then the same but with that number of agents
if amps is provided, then using those link amps

amps would probably need to be something more than just a number. Maybe syntax like 1R2V?

**Comment by therealklanni** [comment]
I like the proposal. I'll take a crack at it when I have time, if someone else doesn't get to it first.

**Comment by impleri** [comment]
Some of this already exists with the range commands, but this would be a really nice addition. Would need to account for both LA types.

**Comment by pklapperich** [comment]
Yeah, I was thinking 1R2V would mean "1 rare link amp, 2 very rare link amps".

What range commands? Recharge distance is the closest thing I see.

**Comment by EvoldicA** [comment]
There is actually code out there that does something similar...  check out [link.js](https://github.com/jdanlewis/ingress-slack)

**Comment by therealklanni** [comment]
Please reopen this issue/pull-request over at [therealklanni/hubot-ingress](https://github.com/therealklanni/hubot-ingress).
