### ISSUE TITLE
Badge Ordering

### ISSUE THREAD

**Issue by jacobjpope** [hubot-scripts/hubot-ingress#42]
Love this script.  2 requests:
1) Could Hubot recite the badges in opposite order he is currently?  For example, it currently recites from oldest added to newest added.
2) Could Hubot prioritize the anomaly badges from newest to oldest anomaly, like the scanner currently does?  So the order would be [Anomaly Badges Newest-Oldest],[All other badges newest-oldest].

Thanks!

**Comment by therealklanni** [comment]
I'm fairly certain we list them alphabetically. I'm hesitant to permanently change their order, because what if other people want them in a specific (different) order? We can't please everyone in this way. However, we could include an option when you ask for the list to reverse the order on-demand.

**Comment by jacobjpope** [comment]
Ah yes, to clarify, this is for the "what badges do I have" command.

**Comment by therealklanni** [comment]
"What badges do I have (in) reverse"

**Comment by therealklanni** [comment]
Oops :)

**Comment by therealklanni** [comment]
Please reopen this issue/pull-request over at [therealklanni/hubot-ingress](https://github.com/therealklanni/hubot-ingress).
