### ISSUE TITLE
`cps on <date>` returns the incorrect date

### ISSUE THREAD

**Issue by Chaotic** [hubot-scripts/hubot-ingress#43]
Attempting to query the cps on a given date is returning date -1

> sambot cps on 8/14/2015
> 
> sambotBOT [2:03 PM] 
> The checkpoints on  Thu, August 13th 2015 occur at:  1AM EDT, 6AM EDT, 11AM EDT, 4PM EDT, 9PM EDT.

Its possible that this is a configuration issue.

Also if you do a query on an invalid date it returns the CPs on invalid date

> sambot cps on august 14th
> 
> sambotBOT [2:01 PM] 
> The checkpoints on Invalid date occur at: Invalid date,Invalid date,Invalid date,Invalid date,Invalid date.

**Comment by drstevens** [comment]
Looks like a timezone thing. Hubot from example above is configured with 
```
HUBOT_CYCLE_TIME_FMT:     hA z
HUBOT_CYCLE_TZ_NAME:      America/New_York
```
Looks like you full date/time string can be specified 
https://github.com/hubot-scripts/hubot-ingress/blob/master/src/cycle-times.coffee#L134

```
drstevens [2:27 PM] 
sambot cps on 8/14/2015 EDT

sambotBOT [2:27 PM] 
The checkpoints on  Fri, August 14th 2015 occur at:  2AM EDT, 7AM EDT, 12PM EDT, 5PM EDT, 10PM EDT.
```
It would be nice to assume string was in current timezone, but not sure if that would conflict with the ability to specify timezone in the request. I'm not that familiar with Date constructors or javascript date libraries in general.

**Comment by therealklanni** [comment]
Yeah, obviously we can assume that times are by default using the `HUBOT_CYCLE_TZ_NAME` timezone. If they specify a timezone in the request, then it would display it in that timezone.

As far as the "invalid date", we should just not respond with anything if the date is invalid. I'd rather have the request fail silently than spam errors to the user/channel.

**Comment by therealklanni** [comment]
Please reopen this issue/pull-request over at [therealklanni/hubot-ingress](https://github.com/therealklanni/hubot-ingress).
