### ISSUE TITLE
intelmap function not working 

### ISSUE THREAD

**Issue by littlehawn1** [hubot-scripts/hubot-ingress#50]
so i am running this on windows and i have the hubot_google_geocode_key in my environment vars with the api key also, i know it works because when i echo %name% it the api key comes back. the problem is that when i am running the bot it will not find any locations, i have a normal google maps script that has no problem finding the location on the maps but when it comes to this script it will not return intel links. any help would be much appreciated

**Comment by drstevens** [comment]
Are environment variables case sensitive on windows? Try `HUBOT_GOOGLE_GEOCODE_KEY`. A key is not strictly necessary. e.g. `curl 'https://maps.googleapis.com/maps/api/geocode/json?address=boston'` should work by itself. The intended behavior was to not use a key if it isn't found, but I'm no coffeescript expert and it's entirely possible this was botched.

I'm assuming that if it doesn't work, and it's not windows being stupid, then it's finding the key in your environment but it isn't valid. Is Google Maps Geocoding API enabled for this key?
Try `curl 'https://maps.googleapis.com/maps/api/geocode/json?address=boston&key=PUT_YOUR_KEY_HERE`

**Comment by therealklanni** [comment]
I do believe env vars are case-sensitive. You only need a key if you expect your bot to get a lot of use from the Google API (it's more limited without a key).

**Comment by therealklanni** [comment]
Please reopen this issue/pull-request over at [therealklanni/hubot-ingress](https://github.com/therealklanni/hubot-ingress).
