### ISSUE TITLE
Multiple levels of mission day need to be added

### ISSUE THREAD

**Issue by DrOverdose** [hubot-scripts/hubot-ingress#52]

**Comment by DrOverdose** [comment]
seems jahan and acoloyte is also missing

**Comment by therealklanni** [comment]
I'm happy to accept a pull-request if you want to tackle it. Thanks for letting me know about the update!

**Comment by DrOverdose** [comment]
code from fork  https://github.com/sleavitt/hubot-ingress seems to have these badges and more, along with other code as well that makes other improvements. fyi

**Comment by sleavitt** [comment]
Pull request https://github.com/hubot-scripts/hubot-ingress/pull/53 has been submitted to address the badges and other issues.

**Comment by EvoldicA** [comment]
The badges mentioned in this issue have been merged to the master.
