### ISSUE TITLE
Split badge on more than just commas

### ISSUE THREAD

**Issue by boolieman** [hubot-scripts/hubot-ingress#54]
I noticed that the bot has issues when interpreting some strings from users who don't fully understand a comma separated list when trying to add badges, would it be possible to change the method of split from `.split(',')` to `.split(/[ ,;]/)` to handle more delimiters that people could use? (i admit to most likely being the only one who would use the `;` but its easy to add)

**Comment by therealklanni** [comment]
I'm happy to accept a PR. 👍

**Comment by therealklanni** [comment]
Please reopen this issue/pull-request over at [therealklanni/hubot-ingress](https://github.com/therealklanni/hubot-ingress).
