### ISSUE TITLE
Request to assist with maintaining package

### ISSUE THREAD

**Issue by sonyatvwebteam** [hubot-scripts/hubot-ingress#58]
As the subject indicates, I would be interested in helping with maintaining this package.

**Comment by therealklanni** [comment]
I would love the help, thanks!

**Comment by therealklanni** [comment]
You have been invited, check your email 👍

**Comment by therealklanni** [comment]
@sonyatvwebteam so just a couple simple things that you probably already know, but I just want to say it to be sure.

Please be aware of changes to the version number being changed in PRs (this happens from time to time). I want to be sure we reject such changes (just ask them to undo it, please). The reason being: the contributor doesn't necessarily know, nor should they decide, when their change will be published. Someone else's PR could be merged and published before theirs, and now there's a version conflict.

Let me know your npm username so I can give you publish access as well. How familiar are you with semver?

**Comment by sonyatvwebteam** [comment]
I am going to open a new issue for this from my personal account (the username will be sleavitt). I was logged into a work account when I opened this issue and didn't realize it. Sorry for the confusion.
