### ISSUE TITLE
I would like to assist with maintaining this... 

### ISSUE THREAD

**Issue by EvoldicA** [hubot-scripts/hubot-ingress#59]
Initially I will only be able to assist with adding new badges and easy things but I should be able to move on to more advanced items as I become more familiar.

**Comment by therealklanni** [comment]
Thanks, I could definitely use the help!

Are you familiar with semver?

**Comment by EvoldicA** [comment]
I did refresh my memory on this (thanks google) when I saw you ask the same question of sleavitt.  :)

**Comment by therealklanni** [comment]
@EvoldicA sounds good. I assume you saw the rest of that discussion as well (regarding package version changes in PRs)?

**Comment by EvoldicA** [comment]
Yup.  I almost commented on the pull request with the version # before you did..

**Comment by therealklanni** [comment]
:metal: I'll get you added. Is your npm username the same?

**Comment by EvoldicA** [comment]
Yup.   evoldica
