### ISSUE TITLE
Request to assist with maintaining package

### ISSUE THREAD

**Issue by sleavitt** [hubot-scripts/hubot-ingress#61]
As the subject indicates, I would be interested in helping with maintaining this package.

Re-opening request from #58, which inadvertently used the wrong username to open the issue.

**Comment by therealklanni** [comment]
Oh, oops! I'll update the contributor to this username instead, thanks.

Copying the questions I had for you from the other issue:

> so just a couple simple things that you probably already know, but I just want to say it to be sure.

> Please be aware of the package version number being changed in PRs (this happens from time to time). I want to be sure we reject such changes (just ask them to undo it, please). The reason being: the contributor doesn't necessarily know, nor should they be the one to decide, when their change will be published. Someone else's PR could be merged and published before theirs, and now there's a version conflict.

> Let me know your npm username so I can give you publish access as well. How familiar are you with semver?

**Comment by sleavitt** [comment]
I have seen that on a few pull requests for hubot-ingress, and I agree that
PRs should not bump the package version number, and that pull requests
should be rejected for that reason. The author of the package should
determine that, not the contributor.

My npm username is sleavitt. As for semver, I presume you mean semantic
versioning, and I deal with it almost daily, as I am a web developer by
trade, programming in Symfony (PHP), along with various Javascript
technologies (npm, bower, etc.), so I consider myself to be pretty familiar
with semantic versioning.

**Comment by therealklanni** [comment]
Great! I'll get you added. Thanks again for offering to help out :metal:

**Comment by therealklanni** [comment]
Would you be open to drafting a CONTRIBUTING.md?

**Comment by therealklanni** [comment]
OK, you're added in npm. GitHub invite to collab here sent.

**Comment by EvoldicA** [comment]
Have you heard of [gitmagic](gitmagic.io)? Sounds interesting.

**Comment by therealklanni** [comment]
I haven't, but it looks like an interesting idea, I'll look into it. Thanks!

**Comment by sleavitt** [comment]
Yes, I would be open to drafting up a CONTRIBUTING.md file for the repo.
