### ISSUE TITLE
Integrate Agent-stats api

### ISSUE THREAD

**Issue by DrOverdose** [hubot-scripts/hubot-ingress#76]
the agent-stats api https://apidocs.agent-stats.com/ would allow the hubot to lookup an agents stats or information and report back after receiving a request for information. I would imagine a group would need to be setup for the community so that the bot can access the information.

examples
USER - Hubot, How much AP do I have? (alternate could be how much ap does @user have)
HUBOT - @user has 39,999,999 as of their last Agent-stats upload on 1-1-2016.

USER - Hubot, How long till I get level 16? (alternate could be how long till @user gets level 16)
HUBOT - @user has 39,999,999 as of their last agent-stats upload on 1-1-2016. Agent Stats Predicts them getting level 16 on 1-2-2016

USER - Hubot, who in our group has the most AP?
HUBOT - According to agent stats @user1 has 200,000,000 ap while @user2 is in second place at 69,00,000 ap.

USER- Hubot, how close to the next Purifier badge am I? (or is @agent)
HUBOT - @user needs to destroy 5000 more resonators to hit the next tier for :purifier:. agent-stats predicts this will occur on 1-1-2017 per the monthly stats. User last updated their stats on 1-1-2016

these are just some examples of possible things that could be asked. I am sure more people could think of additional items.

**Comment by therealklanni** [comment]
Please reopen this issue/pull-request over at [therealklanni/hubot-ingress](https://github.com/therealklanni/hubot-ingress).
